# project_id = "zgexnqpeywpsbrkrfrsu"

[functions.generate-topic]
verify_jwt = false

[functions.evaluate-reading]
verify_jwt = false

[functions.get-daily-topic]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
